parameters:
- name: sdkVersion
  type: string
  default: '8'

steps:
- task: UseDotNet@2
  displayName: Use .NET SDK version ${{ iif(eq(parameters.sdkVersion, ''), 'latest', parameters.sdkVersion ) }}
  inputs:
    packageType: 'sdk'
    version: ${{ parameters.sdkVersion }}
    includePreviewVersions: true
